{"name": "verifying search button is present in Google home page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=69.0.3497.100)\n  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)\n\n", "trace": "  File \"c:\\program files\\python36\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\program files\\python36\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Defination.py\", line 34, in I_am_loading_google_url_as\n    d.loadURL(url)\n  File \"C:\\Users\\Ramesh-Shwetha\\PycharmProjects\\True_Fit_Automation_Framework\\utility\\WrapperDriver.py\", line 38, in loadURL\n    self.driver.get(url)\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I open a browser", "status": "passed", "start": 1540335770378, "stop": 1540335772805}, {"name": "When I am loading google url as \"http://www.google.com\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=69.0.3497.100)\n  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)\n\n", "trace": "  File \"c:\\program files\\python36\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\program files\\python36\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Defination.py\", line 34, in I_am_loading_google_url_as\n    d.loadURL(url)\n  File \"C:\\Users\\Ramesh-Shwetha\\PycharmProjects\\True_Fit_Automation_Framework\\utility\\WrapperDriver.py\", line 38, in loadURL\n    self.driver.get(url)\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\program files\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1540335772806, "stop": 1540335773398}, {"name": "Then I am making sure that search button is present", "status": "skipped", "start": 1540335773401, "stop": 1540335773401}, {"name": "And I am closing the browser", "status": "skipped", "start": 1540335773401, "stop": 1540335773401}], "start": 1540335770376, "stop": 1540335773401, "uuid": "7b08ebbd-aaac-4cc0-b8d4-e101f0c61de4", "historyId": "710d7c02f5c0be8a940bc7ac0750b532", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Testing True Fit"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}